Update build instructions for Linux.
alice-doc/alice-analysis-tutorial pull request #104
Opened 2020-09-03 16:48 UTC by vkucera

2020-09-03 18:07 UTC, mpuccio requested changes

2020-09-03 18:07 UTC, mpuccio commented on building/build.md
>  aliBuild build AliPhysics --defaults user-root6  # without GEANT 3, GEANT 4, DPMJET
Can you please add user-next-root6 here?

2020-09-03 18:43 UTC, vkucera commented on building/build.md
>  aliBuild build AliPhysics --defaults user-root6  # without GEANT 3, GEANT 4, DPMJET
`user-next-root6` is recommended as the default build option.
This is the **Build AliPhysics based on an old ROOT 6 version:** section.
Can you be more specific?

2020-09-07 11:56 UTC, mpuccio commented on building/build.md
>  aliBuild build AliPhysics --defaults user-root6  # without GEANT 3, GEANT 4, DPMJET
yes, @ktf shall we remove the part on the old ROOT from the documentation? I would be very much in favour.

2020-09-07 12:29 UTC, ktf commented on building/build.md
>  aliBuild build AliPhysics --defaults user-root6  # without GEANT 3, GEANT 4, DPMJET
You mean ROOT5? Given this is the analysis tutorial I guess we can.

2020-09-07 12:41 UTC, mpuccio commented on building/build.md
>  aliBuild build AliPhysics --defaults user-root6  # without GEANT 3, GEANT 4, DPMJET
This is even worse, it's about old ROOT 6 versions. But OK, I think we can remove this, @vkucera can you do it? Just remove the full section `Build AliPhysics based on an old ROOT 6 version`

2020-09-07 12:48 UTC, mpuccio approved these changes

2020-09-07 12:48 UTC, merged