added archlinux build instructions
alice-doc/alice-analysis-tutorial pull request #146
Opened 2022-08-01 09:36 UTC by f3sch

Since I use archlinux as my os, I wanted to capture (mostly for myself) how to build O2.

Signed-off-by: Felix Schlepper <felix.schlepper@cern.ch>

2022-08-01 10:10 UTC, mconcas commented
Hi @f3sch, usually we keep track of the officially supported OSs here, or at least of the most commonly shared and supported on best effort basis (like macOS).
Do we plan to have a large/supported use case pool of Arch Linux distros?

As you stated this would be mostly for yourself, so I am not super keen to have this kind of addictions to the official software installation guide.

Anyways cc-ing @ktf

2022-08-03 07:25 UTC, ktf requested changes
I agree with @mconcas that if this is to be included in the official instructions, you should somehow commit to maintain them, even if on a best effort basis. Moreover I would appreciate if before we go ahead and merge this, you made sure the comments I have inline are addressed, instructions distilled to a bare minimum and in particular the upstream version of all the mentioned repositories are used.

2022-08-03 07:25 UTC, ktf commented on building/prereq-arch.md
> +sudo pacman -Syu git angular-cli base-devel base binutils bison boost llvm cmake double-conversion doxygen evtest flatbuffers flex gcc-fortran gdm gettext glfw-x11 graphviz grpc gsl gtest gzip libtoo
How difficult would it be to have a proper Arch metapackage which includes all the dependencies? Could you try to have something like that?

2022-08-03 07:25 UTC, ktf commented on building/prereq-arch.md
> +yay -S autotrace env-modules-tcl
is there a way you can do this in a single command and merge it with the above?

2022-08-03 07:25 UTC, ktf commented on building/prereq-arch.md
> +sudo python setup.py install
If this PR is to be merged, we definitely should use the upstream alibuild. It would also be nice if you had alibuild packaged for Arch and its installation unified with the pacman command above.

2022-08-03 07:25 UTC, ktf commented on building/prereq-arch.md
> +git clone https://github.com/f3sch/alidist.git # my personal fork until I make a PR upstream, but I think the mods are unreconcilable.
Again, if this is to be merged, we should use the upstream version of alidist.

2022-08-03 07:25 UTC, ktf commented on building/prereq-arch.md
> +Your first build will probably fail to GEANT4 not compiling.
Same for the Geant4 business, either you agree on the modifications with @sawenzel and we include them in some -aliceX version, or we should reach to upstream and have it fixed there officially.

2022-08-04 13:47 UTC, ktf commented
I would prefer we close this (without deleting it) and reopen when you are ready to discuss again.

2022-08-04 13:47 UTC, ktf commented
(unless of course you think you will be able to give an answer in the next few weeks).

2022-08-04 14:33 UTC, f3sch commented
Done.

2022-08-04 14:33 UTC, closed without merging

2022-10-11 09:08 UTC, f3sch commented
Giulio Eulisse ***@***.***> writes:

> @ktf requested changes on this pull request.
>
> I agree with @mconcas that if this is to be included in the official instructions, you should somehow commit to maintain
> them, even if on a best effort basis. Moreover I would appreciate if before we go ahead and merge this, you made sure the
> comments I have inline are addressed, instructions distilled to a bare minimum and in particular the upstream version of
> all the mentioned repositories are used.
>
> -------------------------------------------------------------------------------------------------------------------------
>
> In building/prereq-arch.md:
>
>> +ALICE software on ArchLinux is supported on a best effort basis. There is no guarantee that software builds or runs correctly. Support requests might have low priority. We were able to successfully build on:
> +
> +* 5.18.14-arch1-1, with some minor modifications in the sources
> +
> +## Install required system packages
> +
> +With root permissions, _i.e._ `sudo`, update your package sources:
> +
> +```bash
> +sudo pacman -Syu
> +```
> +
> +With root permissions, _i.e._ `sudo`, install the following packages [TODO remove unneeded packages]:
> +
> +```bash
> +sudo pacman -Syu git angular-cli base-devel base binutils bison boost llvm cmake double-conversion doxygen evtest flatbuffers flex gcc-fortran gdm gettext glfw-x11 graphviz grpc gsl gtest gzip libtool m4 meld mlocate openssh parallel pythia8 python-attrs python-bleach python-matplotlib python-pip python-psutil python-wheel python-yaml rapidjson rsync swig xorg-server xorg-xinit xorg-xinput xorg-xrandr xorg-xwininfo xrootd xterm yaml-cpp xsimd
>
> How difficult would it be to have a proper Arch metapackage which includes all the dependencies? Could you try to have
> something like that?
>
> -------------------------------------------------------------------------------------------------------------------------
>
> In building/prereq-arch.md:
>
>> +With root permissions, _i.e._ `sudo`, update your package sources:
> +
> +```bash
> +sudo pacman -Syu
> +```
> +
> +With root permissions, _i.e._ `sudo`, install the following packages [TODO remove unneeded packages]:
> +
> +```bash
> +sudo pacman -Syu git angular-cli base-devel base binutils bison boost llvm cmake double-conversion doxygen evtest flatbuffers flex gcc-fortran gdm gettext glfw-x11 graphviz grpc gsl gtest gzip libtool m4 meld mlocate openssh parallel pythia8 python-attrs python-bleach python-matplotlib python-pip python-psutil python-wheel python-yaml rapidjson rsync swig xorg-server xorg-xinit xorg-xinput xorg-xrandr xorg-xwininfo xrootd xterm yaml-cpp xsimd
> +```
> +
> +Additionally, we need packages from aur.
> +
> +```bash
> +yay -S autotrace env-modules-tcl
>
> is there a way you can do this in a single command and merge it with the above?
>
> -------------------------------------------------------------------------------------------------------------------------
>
> In building/prereq-arch.md:
>
>> +```
> +
> +Additionally, we need packages from aur.
> +
> +```bash
> +yay -S autotrace env-modules-tcl
> +```
> +
> +## Installing aliBuild
> +AliBuild, our build tool, is installed as a standard python package.
> +This is done with:
> +
> +```bash
> +cd ~/alice # or wherever you want to install it, I recommend keep it all in one directory
> +git clone https://github.com/f3sch/alibuild.git # my personal fork until I make a PR upstream cd alibuild
> +sudo python setup.py install
>
> If this PR is to be merged, we definitely should use the upstream alibuild. It would also be nice if you had alibuild
> packaged for Arch and its installation unified with the pacman command above.
>
> -------------------------------------------------------------------------------------------------------------------------
>
> In building/prereq-arch.md:
>
>> +This is done with:
> +
> +```bash
> +cd ~/alice # or wherever you want to install it, I recommend keep it all in one directory
> +git clone https://github.com/f3sch/alibuild.git # my personal fork until I make a PR upstream cd alibuild
> +sudo python setup.py install
> +```
> +
> + Now you should be able to use `aliBuild` as a command.
> + ## Installing alidist
> +To actually build O2 and its dependencies we need the recipes to do so. Normally, `aliBuild init ...` would download those and take care of everything.
> +However, there are some _minor_ modifications we need to make to those recipes [FUN].
> +
> +```bash
> +cd ~/alice
> +git clone https://github.com/f3sch/alidist.git # my personal fork until I make a PR upstream, but I think the mods are unreconcilable.
>
> Again, if this is to be merged, we should use the upstream version of alidist.
>
> -------------------------------------------------------------------------------------------------------------------------
>
> In building/prereq-arch.md:
>
>> +cd ~/alice
> +git clone https://github.com/f3sch/alidist.git # my personal fork until I make a PR upstream, but I think the mods are unreconcilable.
> +git checkout arch
> +```
> +
> +Now you have the correct build recipes.
> +
> +## Building O2
> +At the end of this section you will be guided to document, which tells you how to build O2. Let me take a few sentences on what to do.
> +
> +### First
> +Do not run `aliBuild init ...`! From my understanding this pulls the build recipes itself from upstream, which is not what we want.
> +This botched some builds for me.
> +
> +### Second
> +Your first build will probably fail to GEANT4 not compiling.
>
> Same for the Geant4 business, either you agree on the modifications with @sawenzel and we include them in some -aliceX
> version, or we should reach to upstream and have it fixed there officially.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.


From my understanding there is absolutely nothing planned using arch.
I really just wrote this down mostly for myself.
I would be willing to maintain this on a best effort basis, however I
will first see how much work it is to use the upstream builds.
If okay, will leave this PR open and circle back to it later?

--

cheers
Felix Schlepper