Introduce a new, fast, build method
alice-doc/alice-analysis-tutorial pull request #94
Opened 2020-08-10 18:01 UTC by ktf

2020-08-12 00:20 UTC, ktf commented
@mpuccio could you review and eventually approve?

2020-08-20 09:17 UTC, mpuccio requested changes
This is an excellent new feature, I would just change the small thing about make vs cmake --build and then we can merge

2020-08-20 09:17 UTC, mpuccio commented on building/devel.md
> +make -j 20
Maybe just replace `make` with `cmake --build . --target install -j8`. I put 8 as most of people (like me :( ) still don't have newer, better cpus.

2020-08-20 10:22 UTC, ktf commented on building/devel.md
> +make -j 20
Done.

2020-08-20 18:03 UTC, mpuccio approved these changes

2020-08-20 18:30 UTC, ktf commented
Notice I cannot merge it...

2020-08-21 08:58 UTC, mpuccio commented
Yes, as a matter of fact I cannot either because the test failed. Can you pull from my master branch? There is a fix there.

2020-08-23 19:31 UTC, ktf commented
Done

2020-08-24 09:19 UTC, mpuccio approved these changes

2020-08-24 09:22 UTC, merged